import { useState, useEffect } from "react";
import { useForm, Controller } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";

import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { MediaUpload } from "../MediaUpload"; // Correct path to MediaUpload

// Define Zod schema for category form validation
const categoryFormSchema = z.object({
  name: z.string().min(1, "Category name is required"),
});

export default function CategoryForm({ initialData, onSuccess, onCancel, isDuplicating }) {
  const [categoryPic, setCategoryPic] = useState([]); // For the main category image

  const {
    handleSubmit,
    control,
    reset,
    formState: { errors },
  } = useForm({
    resolver: zodResolver(categoryFormSchema),
    defaultValues: {
      ...(initialData || {}),
      name: initialData?.name || "",
    },
  });

  useEffect(() => {
    if (initialData) {
      const formDataToSet = isDuplicating
        ? { ...initialData, id: undefined }
        : { ...initialData };
      
      reset(formDataToSet);
      // Set initial media if available
      if (initialData.pic) {
        setCategoryPic([{ id: 'existing_pic', url: initialData.pic, type: 'image', file: null }]);
      } else {
        setCategoryPic([]);
      }
    } else {
      reset({
        name: "",
      });
      setCategoryPic([]);
    }
  }, [initialData, reset, isDuplicating]);

      const onSubmit = (data) => {
        const fileToUpload = categoryPic.length > 0 && categoryPic[0].file ? categoryPic[0].file : null;
        const existingPicUrl = categoryPic.length > 0 && categoryPic[0].url && !categoryPic[0].file ? categoryPic[0].url : null;
        const picRemoved = initialData?.pic && categoryPic.length === 0;
  
        const finalData = {
          ...data,
          file: fileToUpload,
          image_url: existingPicUrl, // Add this line
          pic_removed: picRemoved,
          id: (isDuplicating || !initialData) ? undefined : initialData.id,
        };
        onSuccess(finalData);
      };
  return (
    <div className="p-6 mx-auto space-y-8">
      <form onSubmit={handleSubmit(onSubmit)} className="space-y-8">
        <Card>
          <CardHeader>
            <CardTitle>Category Information</CardTitle>
          </CardHeader>
          <CardContent className="space-y-6">
            <div className="space-y-2">
              <Label htmlFor="name">
                Category Name <span className="text-red-500">*</span>
              </Label>
              <Controller
                name="name"
                control={control}
                render={({ field }) => (
                  <Input
                    id="name"
                    placeholder="Enter category name"
                    {...field}
                  />
                )}
              />
              {errors.name && (
                <p className="text-sm text-red-500">{errors.name.message}</p>
              )}
            </div>

            <div className="space-y-2">
              <Label>Category Image (Main)</Label>
              <MediaUpload
                initialMedia={categoryPic}
                onMediaChange={setCategoryPic}
                maxFiles={1}
                maxFileSizeMb={5}
                allowMultiple={false}
                allowedTypes={["image/*"]}
              />
            </div>
            {/* The thumbnail is assumed to be generated by the backend from the main image */}
            {/* If a separate thumbnail upload is desired, another MediaUpload component would go here */}
          </CardContent>
        </Card>

        <div className="sticky bottom-0 flex gap-3 p-6 bg-background border-t">
          <Button type="submit" size="lg">
            {initialData ? "Save Changes" : `Add Category`}
          </Button>
          <Button type="button" variant="outline" size="lg" onClick={onCancel}>
            Cancel
          </Button>
        </div>
      </form>
    </div>
  );
}
