/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertiesIndexRouteImport } from './routes/properties/index'
import { Route as MapsIndexRouteImport } from './routes/maps/index'
import { Route as FilesIndexRouteImport } from './routes/files/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardUsersRouteImport } from './routes/dashboard/users'
import { Route as DashboardSocietiesRouteImport } from './routes/dashboard/societies'
import { Route as DashboardQueriesRouteImport } from './routes/dashboard/queries'
import { Route as DashboardPropertiesRouteImport } from './routes/dashboard/properties'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardPhasesRouteImport } from './routes/dashboard/phases'
import { Route as DashboardMapsRouteImport } from './routes/dashboard/maps'
import { Route as DashboardLandingPageRouteImport } from './routes/dashboard/landing-page'
import { Route as DashboardFilesRouteImport } from './routes/dashboard/files'
import { Route as DashboardCitiesRouteImport } from './routes/dashboard/cities'
import { Route as DashboardCategoriesRouteImport } from './routes/dashboard/categories'
import { Route as DashboardCalculatorTransferFeesRouteImport } from './routes/dashboard/calculator-transfer-fees'
import { Route as DashboardCalculatorTaxRatesRouteImport } from './routes/dashboard/calculator-tax-rates'
import { Route as DashboardCalculatorRatesRouteImport } from './routes/dashboard/calculator-rates'
import { Route as DashboardCalculatorPropertyTypesRouteImport } from './routes/dashboard/calculator-property-types'
import { Route as DashboardCalculatorPhasesRouteImport } from './routes/dashboard/calculator-phases'
import { Route as DashboardCalculatorFeesRouteImport } from './routes/dashboard/calculator-fees'
import { Route as DashboardCalculatorFeeRulesRouteImport } from './routes/dashboard/calculator-fee-rules'
import { Route as DashboardCalculatorBlocksRouteImport } from './routes/dashboard/calculator-blocks'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as authAcceptInviteRouteImport } from './routes/(auth)/accept-invite'
import { Route as PropertiesIdIndexRouteImport } from './routes/properties/$id/index'

const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const MapsIndexRoute = MapsIndexRouteImport.update({
  id: '/maps/',
  path: '/maps/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesIndexRoute = FilesIndexRouteImport.update({
  id: '/files/',
  path: '/files/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSocietiesRoute = DashboardSocietiesRouteImport.update({
  id: '/societies',
  path: '/societies',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardQueriesRoute = DashboardQueriesRouteImport.update({
  id: '/queries',
  path: '/queries',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPropertiesRoute = DashboardPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPhasesRoute = DashboardPhasesRouteImport.update({
  id: '/phases',
  path: '/phases',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMapsRoute = DashboardMapsRouteImport.update({
  id: '/maps',
  path: '/maps',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLandingPageRoute = DashboardLandingPageRouteImport.update({
  id: '/landing-page',
  path: '/landing-page',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFilesRoute = DashboardFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCitiesRoute = DashboardCitiesRouteImport.update({
  id: '/cities',
  path: '/cities',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCategoriesRoute = DashboardCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCalculatorTransferFeesRoute =
  DashboardCalculatorTransferFeesRouteImport.update({
    id: '/calculator-transfer-fees',
    path: '/calculator-transfer-fees',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardCalculatorTaxRatesRoute =
  DashboardCalculatorTaxRatesRouteImport.update({
    id: '/calculator-tax-rates',
    path: '/calculator-tax-rates',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardCalculatorRatesRoute =
  DashboardCalculatorRatesRouteImport.update({
    id: '/calculator-rates',
    path: '/calculator-rates',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardCalculatorPropertyTypesRoute =
  DashboardCalculatorPropertyTypesRouteImport.update({
    id: '/calculator-property-types',
    path: '/calculator-property-types',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardCalculatorPhasesRoute =
  DashboardCalculatorPhasesRouteImport.update({
    id: '/calculator-phases',
    path: '/calculator-phases',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardCalculatorFeesRoute = DashboardCalculatorFeesRouteImport.update({
  id: '/calculator-fees',
  path: '/calculator-fees',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCalculatorFeeRulesRoute =
  DashboardCalculatorFeeRulesRouteImport.update({
    id: '/calculator-fee-rules',
    path: '/calculator-fee-rules',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardCalculatorBlocksRoute =
  DashboardCalculatorBlocksRouteImport.update({
    id: '/calculator-blocks',
    path: '/calculator-blocks',
    getParentRoute: () => DashboardRoute,
  } as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authAcceptInviteRoute = authAcceptInviteRouteImport.update({
  id: '/(auth)/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIdIndexRoute = PropertiesIdIndexRouteImport.update({
  id: '/properties/$id/',
  path: '/properties/$id/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calculator': typeof CalculatorRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/accept-invite': typeof authAcceptInviteRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/reset-password': typeof authResetPasswordRoute
  '/dashboard/calculator-blocks': typeof DashboardCalculatorBlocksRoute
  '/dashboard/calculator-fee-rules': typeof DashboardCalculatorFeeRulesRoute
  '/dashboard/calculator-fees': typeof DashboardCalculatorFeesRoute
  '/dashboard/calculator-phases': typeof DashboardCalculatorPhasesRoute
  '/dashboard/calculator-property-types': typeof DashboardCalculatorPropertyTypesRoute
  '/dashboard/calculator-rates': typeof DashboardCalculatorRatesRoute
  '/dashboard/calculator-tax-rates': typeof DashboardCalculatorTaxRatesRoute
  '/dashboard/calculator-transfer-fees': typeof DashboardCalculatorTransferFeesRoute
  '/dashboard/categories': typeof DashboardCategoriesRoute
  '/dashboard/cities': typeof DashboardCitiesRoute
  '/dashboard/files': typeof DashboardFilesRoute
  '/dashboard/landing-page': typeof DashboardLandingPageRoute
  '/dashboard/maps': typeof DashboardMapsRoute
  '/dashboard/phases': typeof DashboardPhasesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/properties': typeof DashboardPropertiesRoute
  '/dashboard/queries': typeof DashboardQueriesRoute
  '/dashboard/societies': typeof DashboardSocietiesRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/files': typeof FilesIndexRoute
  '/maps': typeof MapsIndexRoute
  '/properties': typeof PropertiesIndexRoute
  '/properties/$id': typeof PropertiesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calculator': typeof CalculatorRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/accept-invite': typeof authAcceptInviteRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/reset-password': typeof authResetPasswordRoute
  '/dashboard/calculator-blocks': typeof DashboardCalculatorBlocksRoute
  '/dashboard/calculator-fee-rules': typeof DashboardCalculatorFeeRulesRoute
  '/dashboard/calculator-fees': typeof DashboardCalculatorFeesRoute
  '/dashboard/calculator-phases': typeof DashboardCalculatorPhasesRoute
  '/dashboard/calculator-property-types': typeof DashboardCalculatorPropertyTypesRoute
  '/dashboard/calculator-rates': typeof DashboardCalculatorRatesRoute
  '/dashboard/calculator-tax-rates': typeof DashboardCalculatorTaxRatesRoute
  '/dashboard/calculator-transfer-fees': typeof DashboardCalculatorTransferFeesRoute
  '/dashboard/categories': typeof DashboardCategoriesRoute
  '/dashboard/cities': typeof DashboardCitiesRoute
  '/dashboard/files': typeof DashboardFilesRoute
  '/dashboard/landing-page': typeof DashboardLandingPageRoute
  '/dashboard/maps': typeof DashboardMapsRoute
  '/dashboard/phases': typeof DashboardPhasesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/properties': typeof DashboardPropertiesRoute
  '/dashboard/queries': typeof DashboardQueriesRoute
  '/dashboard/societies': typeof DashboardSocietiesRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard': typeof DashboardIndexRoute
  '/files': typeof FilesIndexRoute
  '/maps': typeof MapsIndexRoute
  '/properties': typeof PropertiesIndexRoute
  '/properties/$id': typeof PropertiesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calculator': typeof CalculatorRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/(auth)/accept-invite': typeof authAcceptInviteRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/dashboard/calculator-blocks': typeof DashboardCalculatorBlocksRoute
  '/dashboard/calculator-fee-rules': typeof DashboardCalculatorFeeRulesRoute
  '/dashboard/calculator-fees': typeof DashboardCalculatorFeesRoute
  '/dashboard/calculator-phases': typeof DashboardCalculatorPhasesRoute
  '/dashboard/calculator-property-types': typeof DashboardCalculatorPropertyTypesRoute
  '/dashboard/calculator-rates': typeof DashboardCalculatorRatesRoute
  '/dashboard/calculator-tax-rates': typeof DashboardCalculatorTaxRatesRoute
  '/dashboard/calculator-transfer-fees': typeof DashboardCalculatorTransferFeesRoute
  '/dashboard/categories': typeof DashboardCategoriesRoute
  '/dashboard/cities': typeof DashboardCitiesRoute
  '/dashboard/files': typeof DashboardFilesRoute
  '/dashboard/landing-page': typeof DashboardLandingPageRoute
  '/dashboard/maps': typeof DashboardMapsRoute
  '/dashboard/phases': typeof DashboardPhasesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/properties': typeof DashboardPropertiesRoute
  '/dashboard/queries': typeof DashboardQueriesRoute
  '/dashboard/societies': typeof DashboardSocietiesRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/files/': typeof FilesIndexRoute
  '/maps/': typeof MapsIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/properties/$id/': typeof PropertiesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/calculator'
    | '/contact'
    | '/dashboard'
    | '/privacy-policy'
    | '/accept-invite'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/dashboard/calculator-blocks'
    | '/dashboard/calculator-fee-rules'
    | '/dashboard/calculator-fees'
    | '/dashboard/calculator-phases'
    | '/dashboard/calculator-property-types'
    | '/dashboard/calculator-rates'
    | '/dashboard/calculator-tax-rates'
    | '/dashboard/calculator-transfer-fees'
    | '/dashboard/categories'
    | '/dashboard/cities'
    | '/dashboard/files'
    | '/dashboard/landing-page'
    | '/dashboard/maps'
    | '/dashboard/phases'
    | '/dashboard/profile'
    | '/dashboard/properties'
    | '/dashboard/queries'
    | '/dashboard/societies'
    | '/dashboard/users'
    | '/dashboard/'
    | '/files'
    | '/maps'
    | '/properties'
    | '/properties/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/calculator'
    | '/contact'
    | '/privacy-policy'
    | '/accept-invite'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/dashboard/calculator-blocks'
    | '/dashboard/calculator-fee-rules'
    | '/dashboard/calculator-fees'
    | '/dashboard/calculator-phases'
    | '/dashboard/calculator-property-types'
    | '/dashboard/calculator-rates'
    | '/dashboard/calculator-tax-rates'
    | '/dashboard/calculator-transfer-fees'
    | '/dashboard/categories'
    | '/dashboard/cities'
    | '/dashboard/files'
    | '/dashboard/landing-page'
    | '/dashboard/maps'
    | '/dashboard/phases'
    | '/dashboard/profile'
    | '/dashboard/properties'
    | '/dashboard/queries'
    | '/dashboard/societies'
    | '/dashboard/users'
    | '/dashboard'
    | '/files'
    | '/maps'
    | '/properties'
    | '/properties/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/calculator'
    | '/contact'
    | '/dashboard'
    | '/privacy-policy'
    | '/(auth)/accept-invite'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/reset-password'
    | '/dashboard/calculator-blocks'
    | '/dashboard/calculator-fee-rules'
    | '/dashboard/calculator-fees'
    | '/dashboard/calculator-phases'
    | '/dashboard/calculator-property-types'
    | '/dashboard/calculator-rates'
    | '/dashboard/calculator-tax-rates'
    | '/dashboard/calculator-transfer-fees'
    | '/dashboard/categories'
    | '/dashboard/cities'
    | '/dashboard/files'
    | '/dashboard/landing-page'
    | '/dashboard/maps'
    | '/dashboard/phases'
    | '/dashboard/profile'
    | '/dashboard/properties'
    | '/dashboard/queries'
    | '/dashboard/societies'
    | '/dashboard/users'
    | '/dashboard/'
    | '/files/'
    | '/maps/'
    | '/properties/'
    | '/properties/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CalculatorRoute: typeof CalculatorRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  authAcceptInviteRoute: typeof authAcceptInviteRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  FilesIndexRoute: typeof FilesIndexRoute
  MapsIndexRoute: typeof MapsIndexRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
  PropertiesIdIndexRoute: typeof PropertiesIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/': {
      id: '/properties/'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps/': {
      id: '/maps/'
      path: '/maps'
      fullPath: '/maps'
      preLoaderRoute: typeof MapsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files/': {
      id: '/files/'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/societies': {
      id: '/dashboard/societies'
      path: '/societies'
      fullPath: '/dashboard/societies'
      preLoaderRoute: typeof DashboardSocietiesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/queries': {
      id: '/dashboard/queries'
      path: '/queries'
      fullPath: '/dashboard/queries'
      preLoaderRoute: typeof DashboardQueriesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/properties': {
      id: '/dashboard/properties'
      path: '/properties'
      fullPath: '/dashboard/properties'
      preLoaderRoute: typeof DashboardPropertiesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/phases': {
      id: '/dashboard/phases'
      path: '/phases'
      fullPath: '/dashboard/phases'
      preLoaderRoute: typeof DashboardPhasesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/maps': {
      id: '/dashboard/maps'
      path: '/maps'
      fullPath: '/dashboard/maps'
      preLoaderRoute: typeof DashboardMapsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/landing-page': {
      id: '/dashboard/landing-page'
      path: '/landing-page'
      fullPath: '/dashboard/landing-page'
      preLoaderRoute: typeof DashboardLandingPageRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/files': {
      id: '/dashboard/files'
      path: '/files'
      fullPath: '/dashboard/files'
      preLoaderRoute: typeof DashboardFilesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cities': {
      id: '/dashboard/cities'
      path: '/cities'
      fullPath: '/dashboard/cities'
      preLoaderRoute: typeof DashboardCitiesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/categories': {
      id: '/dashboard/categories'
      path: '/categories'
      fullPath: '/dashboard/categories'
      preLoaderRoute: typeof DashboardCategoriesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/calculator-transfer-fees': {
      id: '/dashboard/calculator-transfer-fees'
      path: '/calculator-transfer-fees'
      fullPath: '/dashboard/calculator-transfer-fees'
      preLoaderRoute: typeof DashboardCalculatorTransferFeesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/calculator-tax-rates': {
      id: '/dashboard/calculator-tax-rates'
      path: '/calculator-tax-rates'
      fullPath: '/dashboard/calculator-tax-rates'
      preLoaderRoute: typeof DashboardCalculatorTaxRatesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/calculator-rates': {
      id: '/dashboard/calculator-rates'
      path: '/calculator-rates'
      fullPath: '/dashboard/calculator-rates'
      preLoaderRoute: typeof DashboardCalculatorRatesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/calculator-property-types': {
      id: '/dashboard/calculator-property-types'
      path: '/calculator-property-types'
      fullPath: '/dashboard/calculator-property-types'
      preLoaderRoute: typeof DashboardCalculatorPropertyTypesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/calculator-phases': {
      id: '/dashboard/calculator-phases'
      path: '/calculator-phases'
      fullPath: '/dashboard/calculator-phases'
      preLoaderRoute: typeof DashboardCalculatorPhasesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/calculator-fees': {
      id: '/dashboard/calculator-fees'
      path: '/calculator-fees'
      fullPath: '/dashboard/calculator-fees'
      preLoaderRoute: typeof DashboardCalculatorFeesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/calculator-fee-rules': {
      id: '/dashboard/calculator-fee-rules'
      path: '/calculator-fee-rules'
      fullPath: '/dashboard/calculator-fee-rules'
      preLoaderRoute: typeof DashboardCalculatorFeeRulesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/calculator-blocks': {
      id: '/dashboard/calculator-blocks'
      path: '/calculator-blocks'
      fullPath: '/dashboard/calculator-blocks'
      preLoaderRoute: typeof DashboardCalculatorBlocksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/accept-invite': {
      id: '/(auth)/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof authAcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$id/': {
      id: '/properties/$id/'
      path: '/properties/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof PropertiesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardCalculatorBlocksRoute: typeof DashboardCalculatorBlocksRoute
  DashboardCalculatorFeeRulesRoute: typeof DashboardCalculatorFeeRulesRoute
  DashboardCalculatorFeesRoute: typeof DashboardCalculatorFeesRoute
  DashboardCalculatorPhasesRoute: typeof DashboardCalculatorPhasesRoute
  DashboardCalculatorPropertyTypesRoute: typeof DashboardCalculatorPropertyTypesRoute
  DashboardCalculatorRatesRoute: typeof DashboardCalculatorRatesRoute
  DashboardCalculatorTaxRatesRoute: typeof DashboardCalculatorTaxRatesRoute
  DashboardCalculatorTransferFeesRoute: typeof DashboardCalculatorTransferFeesRoute
  DashboardCategoriesRoute: typeof DashboardCategoriesRoute
  DashboardCitiesRoute: typeof DashboardCitiesRoute
  DashboardFilesRoute: typeof DashboardFilesRoute
  DashboardLandingPageRoute: typeof DashboardLandingPageRoute
  DashboardMapsRoute: typeof DashboardMapsRoute
  DashboardPhasesRoute: typeof DashboardPhasesRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardPropertiesRoute: typeof DashboardPropertiesRoute
  DashboardQueriesRoute: typeof DashboardQueriesRoute
  DashboardSocietiesRoute: typeof DashboardSocietiesRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCalculatorBlocksRoute: DashboardCalculatorBlocksRoute,
  DashboardCalculatorFeeRulesRoute: DashboardCalculatorFeeRulesRoute,
  DashboardCalculatorFeesRoute: DashboardCalculatorFeesRoute,
  DashboardCalculatorPhasesRoute: DashboardCalculatorPhasesRoute,
  DashboardCalculatorPropertyTypesRoute: DashboardCalculatorPropertyTypesRoute,
  DashboardCalculatorRatesRoute: DashboardCalculatorRatesRoute,
  DashboardCalculatorTaxRatesRoute: DashboardCalculatorTaxRatesRoute,
  DashboardCalculatorTransferFeesRoute: DashboardCalculatorTransferFeesRoute,
  DashboardCategoriesRoute: DashboardCategoriesRoute,
  DashboardCitiesRoute: DashboardCitiesRoute,
  DashboardFilesRoute: DashboardFilesRoute,
  DashboardLandingPageRoute: DashboardLandingPageRoute,
  DashboardMapsRoute: DashboardMapsRoute,
  DashboardPhasesRoute: DashboardPhasesRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardPropertiesRoute: DashboardPropertiesRoute,
  DashboardQueriesRoute: DashboardQueriesRoute,
  DashboardSocietiesRoute: DashboardSocietiesRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CalculatorRoute: CalculatorRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  authAcceptInviteRoute: authAcceptInviteRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  FilesIndexRoute: FilesIndexRoute,
  MapsIndexRoute: MapsIndexRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
  PropertiesIdIndexRoute: PropertiesIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
